// Copyright 2025 Axon Genesis. All rights reserved.
// AxonGenesis.com
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.

#if UNITY_EDITOR

using UnityEditor;
using UnityEngine;

namespace AxonGenesis
{
    [CustomEditor(typeof(MotionPathNode))]
    [CanEditMultipleObjects]
    public class MotionPathNodeEditor : AxonGenesisEditor<MotionPathNode, MotionPathNodeEdit> { }

    sealed public class MotionPathNodeEdit : AxonGenesisBehaviorEdit<MotionPathNode>
    {
        SerializedProperty IsAutoTangents;
        SerializedProperty AutoTangentWeight;
        SerializedProperty OnNodeTriggered;

        public bool hasLastPosition;
        Vector3 lastPosition = Vector3.zero;
        Quaternion lastRotation = Quaternion.identity;


        public MotionPathNodeEdit() { }

        public MotionPathNodeEdit(MotionPathNode _target)
        {
            target = _target;
        }

        public override void OnEnable()
        {
            base.OnEnable();
            DocumentationURL = "https://axongenesis.gitbook.io/timeflow/reference/behaviors/animation/motion-path#motion-path-nodes";

            /// The tangents cannot be multi-edited with property fields because they are not serialized.
            IsAutoTangents = editor.serializedObject.FindProperty("_IsAutoTangents");
            AutoTangentWeight = editor.serializedObject.FindProperty("AutoTangentWeight");
            OnNodeTriggered = editor.serializedObject.FindProperty("OnNodeTriggered");
        }

        public override void GUISetup()
        {
            base.GUISetup();
        }

        public override void GUIMenu()
        {
        }

        public override void OnMultiEditGUI()
        {
            OnInspectorGUI();
        }

        public override void OnInspectorGUI()
        {
            /// Null references might occur momentarily during script recompile or initialization
            if (target.Key == null || target.Key.Channel == null) return;

            /// Check whether any changes have been made directly to the node transform - but ignore during playback.
            if (Timeflow.Active != null && !Timeflow.Active.IsPlaying && hasLastPosition && target.MotionPath != null) {
                if (lastPosition != target.transform.localPosition || lastRotation != target.transform.localRotation) {
                    target.MotionPath.Refresh();
                }
            }

            bool lockTimeChanged = false;
            bool lockValueChanged = false;
            bool unifyChanged = false;
            bool showTangentsChanged = false;
            bool vectorInChanged = false;
            bool vectorOutChanged = false;
            bool reset = false;

            AxonGUI.BeginHorizontal();
            if (!IsMultiObject) {
                AxonGUI.BeginDisabledGroup(target.Key.LockTime);
                AxonGUI.UndoName = "Set Keyframe Time";
                target.KeyTime = AxonGUI.FieldFloat(target, "Time", target.KeyTime);
                AxonGUI.EndDisabledGroup();
            }
            else {
                AxonGUI.Label("Time");
            }

            AxonGUI.UndoName = "Set Keyframe Lock Time";
            bool lockTime = AxonGUI.FieldToggleInline(target, "Lock Time", target.Key.LockTime);
            if (target.Key.LockTime != lockTime) {
                target.Key.LockTime = lockTime;
                lockTimeChanged = true;
            }

            AxonGUI.UndoName = "Set Keyframe Lock Value";
            bool lockValue = AxonGUI.FieldToggleInline(target, "Value", target.Key.LockValue);
            if (target.Key.LockValue != lockValue) {
                target.Key.LockValue = lockValue;
                lockValueChanged = true;
            }
            AxonGUI.EndHorizontal();

            if (!IsMultiObject) {
                AxonGUI.BeginHorizontal();
                bool isExposed = target.Key.ExposedID != 0;
                AxonGUI.UndoName = "Set Keyframe Exposed";
                AxonGUI.SetTooltip("Expose a keyframe to set its value remotely via scripting, referring to it by name using Keyframer.SetExposedKeyframe(). Be sure to use a unique name. A random ID is generated by default.");
                bool ex = AxonGUI.FieldToggle(target, "Expose ID", isExposed);
                if (ex != isExposed) {
                    if (ex) {
                        target.Key.ExposedID = (int)(Random.value * 99999f);
                        Keyframe.RegisterExposedKeyframe(target.Key);
                    }
                    else {
                        target.Key.ExposedID = 0;
                        Keyframe.UnregisterExposedKeyframe(target.Key);
                    }
                }
                if (ex) {
                    AxonGUI.UndoName = "Set Keyframe Exposed ID";
                    if (target.Key.ExposedID == 0) target.Key.ExposedID = (int)(Random.value * 99999f);
                    target.Key.ExposedID = AxonGUI.FieldIntInline(target, target.Key.ExposedID);
                }
                AxonGUI.EndHorizontal();
            }

            AxonGUI.SetTooltip("Automatically calculated distance from the previous keyframe to this one. This value is read-only.");
            AxonGUI.FieldFloat(target, "Distance", target.Distance);

#if AXON_DEVELOPMENT
                AxonGUI.BeginDisabledGroup(target.Key.LockValue);
                AxonGUI.BeginHorizontal();
                AxonGUI.UndoName = "Set Keyframe Velocity";
                target.Velocity = AxonGUI.FieldFloat("Velocity", target.Velocity);
                AxonGUI.UndoName = "Set Keyframe Velocity Time";
                target.VelocityTime = AxonGUI.FieldFloatInline("Time", target.VelocityTime);
                AxonGUI.UndoName = "Set Keyframe Velocity Midpoint";
                target.VelocityMidpoint = AxonGUI.FieldFloatInline("Midpoint", target.VelocityMidpoint);
                AxonGUI.EndHorizontal();
#endif

            if (target.Key.Channel.Interpolation == TimeflowChannel.Interpolations.Bezier && target.Key.Channel.ShowTangents) {
                AxonGUI.BeginHorizontal();
                EditorGUILayout.PropertyField(IsAutoTangents, new GUIContent("Auto Calculate", "If enabled, the tangents are automatically calculated based on the position of the keyframe in a path."));
                float lw = EditorGUIUtility.labelWidth;
                EditorGUIUtility.labelWidth = 60f;
                EditorGUILayout.PropertyField(AutoTangentWeight,
                    new GUIContent("Weight", "Determines the amount (multiplier) of the Auto Tangent Ratio. Use this to shorten or expand auto-calculated tangents for each node."),
                    GUILayout.Width(120));
                EditorGUIUtility.labelWidth = lw;
                AxonGUI.EndHorizontal();

                AxonGUI.BeginHorizontal();
                AxonGUI.UndoName = "Set Keyframe Unify Tangents";
                AxonGUI.SetTooltip("Unified tangents create a continuous line, so the in and outpoints are on the same angle. If disabled, each tangent may have an independent angle, to create a hard angle in the path.");
                bool unify = AxonGUI.FieldToggle(target, "Unify Tangents", target.Key.UnifyTangents);
                if (target.Key.UnifyTangents != unify) {
                    target.Key.UnifyTangents = unify;
                    unifyChanged = true;
                }
                if (AxonGUI.ButtonInline("Reset")) {
                    reset = true;
                    if (target.MotionPath != null) target.MotionPath.CalculateAutoTangent(target);
                }
                AxonGUI.EndHorizontal();

                AxonGUI.BeginHorizontal();
                AxonGUI.UndoName = "Set Keyframe Show Tangents";
                bool showTangents = AxonGUI.FieldToggle(target, "Show Tangents", target.ShowTangents);
                if (target.ShowTangents != showTangents) {
                    target.ShowTangents = showTangents;
                    showTangentsChanged = true;
                }
                AxonGUI.EndHorizontal();


                AxonGUI.BeginHorizontal();
                AxonGUI.UndoName = "Set Keyframe Use Events";
                target.UseEvents = AxonGUI.FieldToggle(target, "Use Events", target.UseEvents);
                if (target.UseEvents) {
                    EditorGUILayout.PropertyField(OnNodeTriggered, new GUIContent("On Node Triggered", "Triggers a UnityEvent when the node is traversed."));
                }
                AxonGUI.EndHorizontal();



                EditorGUI.BeginDisabledGroup(target.ShowTangents);
                AxonGUI.BeginHorizontal();

                AxonGUI.UndoName = "Set Keyframe In Tangent";
                Vector3 vectorIn = AxonGUI.FieldVector3(target, "In ", target.Key.VectorInTangent);
                if (target.Key.VectorInTangent != vectorIn) {
                    target.Key.VectorInTangent = vectorIn;
                    vectorInChanged = true;
                }
                AxonGUI.EndHorizontal();

                AxonGUI.BeginHorizontal();
                AxonGUI.UndoName = "Set Keyframe Out Tangent";
                Vector3 vectorOut = AxonGUI.FieldVector3(target, "Out ", target.Key.VectorOutTangent);
                if (target.Key.VectorOutTangent != vectorOut) {
                    target.Key.VectorOutTangent = vectorOut;
                    vectorOutChanged = true;
                }
                AxonGUI.EndHorizontal();
                EditorGUI.EndDisabledGroup();


                if (GUI.changed) {
                    if (IsMultiObject) {
                        /// Manually implement multi-object edit since the Key object is not serialized
                        foreach (GameObject obj in Selection.gameObjects) {
                            if (obj.TryGetComponent<MotionPathNode>(out MotionPathNode node)) {
                                if (lockTimeChanged) {
                                    node.Key.LockTime = lockTime;
                                }
                                if (lockValueChanged) {
                                    node.Key.LockValue = lockValue;
                                }
                                if (unifyChanged) {
                                    node.Key.UnifyTangents = unify;
                                    node.IsAutoTangents = false;
                                }
                                if (showTangentsChanged) {
                                    node.Key.ShowTangents = showTangents;
                                }
                                if (vectorInChanged) {
                                    node.Key.VectorInTangent = vectorIn;
                                    node.IsAutoTangents = false;
                                }
                                if (vectorOutChanged) {
                                    node.Key.VectorOutTangent = vectorOut;
                                    node.IsAutoTangents = false;
                                }
                                if (reset) {
                                    target.MotionPath.CalculateAutoTangent(node);
                                    node.IsAutoTangents = false;
                                }
                            }
                        }
                    }

                    AnimatorInfo.Init(target.gameObject, true);
                    editor.serializedObject.ApplyModifiedProperties();
                    target.MotionPath.Refresh();
                    EditorUtility.SetDirty(target);
                }
            }


            AxonGUI.HelpBox("This game object and its children are managed by Motion Path. Please do not delete or move this object or its children. " +
                "It is also recommended to avoid adding any other objects as children to this hierarchy. Instead use Follow or Channel Link to relate motions " +
                "to motion path node objects. Please refer to the documentation for more information.", MessageType.Info, true);


            hasLastPosition = true;
            lastPosition = target.transform.localPosition;
            lastRotation = target.transform.localRotation;
        }

        public override void OnSceneGUI()
        {
            if (target != null) {
                target.OnDrawGizmos();
            }
        }
    }

}//AxonGenesis

#endif