// Copyright 2025 Axon Genesis. All rights reserved.
// AxonGenesis.com
// THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY 
// KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.

using System;
using UnityEngine;

#if UNITY_EDITOR
using UnityEditor;
#endif

namespace AxonGenesis
{
    /// <summary>
    /// This encapsulates the data generated by Tween into a TimeflowChannel so it can be displayed in the
    /// Timeflow view and layered with other channels.
    /// </summary>
    [Serializable]
    [UnityEngine.Scripting.APIUpdating.MovedFrom(true, "AxonGenesis", "Assembly-CSharp", "TweenChannel")]
    sealed public class TweenChannel : TimeflowChannel
    {
        [NonSerialized]
        private Tween _TweenParent;

        public TweenChannel(Tween parent) : base(parent)
        {
            _TweenParent = parent;
        }

        public TweenChannel(Tween parent, TweenChannel copy) : base(parent)
        {
            _TweenParent = parent;
            Copy(copy);
        }

        public override void Copy(TimeflowChannel src, bool includeStyle = true)
        {
            Tween parent = _TweenParent;
            base.Copy(src);
            SetParent(parent);

            Name = src.Name;
            ToProperty.Name = src.ToProperty.Name;
            ToProperty.SwitchGameObject(_TweenParent.gameObject);
        }

        public override void SetParent(TimeflowBehavior parent)
        {
            base.SetParent(parent);
            _TweenParent = parent as Tween;
            _HasProperty = true;
        }

        /// <summary>
        /// Returns false since there are no keyframes generated on a TweenChannel
        /// </summary>
        public override bool SupportsKeyframes {
            get {
                return false;
            }
        }

        public override bool IsLoopSupported {
            get {
                return false;
            }
        }

        #region INTERPOLATION

        /// <summary>
        /// Overrided to disable
        /// </summary>
        public override bool CanInterpolate {
            get {
                if (_Interpolation != Interpolations.None) _Interpolation = Interpolations.None;
                return false;
            }
        }

        public override float InterpolateValue(float time, bool apply, bool isLocalTime)
        {
            float value = 0;

            if (_TweenParent != null && ToProperty != null) {
                float intime = time;
                if(!isLocalTime) time = LocalTime(time);
                value = _TweenParent.InterpolateValue(ToProperty, time, 1f, apply);
            }
            return value;
        }

        public override Vector2 InterpolateVector2(float time, bool apply, bool isLocalTime)
        {
            Vector2 value = Vector2.zero;
            if (_TweenParent != null && ToProperty != null) {
                if (!isLocalTime) time = LocalTime(time);
                value = (Vector2)_TweenParent.InterpolateVector(ToProperty, time, 1f, apply);
            }
            return value;
        }

        public override Vector3 InterpolateVector3(float time, bool apply, bool isLocalTime)
        {
            Vector3 value = Vector3.zero;
            if (_TweenParent != null && ToProperty != null) {
                if (!isLocalTime) time = LocalTime(time);
                value = (Vector3)_TweenParent.InterpolateVector(ToProperty, time, 1f, apply);
            }
            return value;
        }

        public override Vector4 InterpolateVector4(float time, bool apply, bool isLocalTime)
        {
            Vector4 value = Vector4.zero;
            if (_TweenParent != null && ToProperty != null) {
                if (!isLocalTime) time = LocalTime(time);
                value = _TweenParent.InterpolateVector(ToProperty, time, 1f, apply);
            }
            return value;
        }

        public override Color InterpolateColor(float time, bool apply, bool isLocalTime)
        {
            Color value = Color.black;
            if (_TweenParent != null && ToProperty != null) {
                if (!isLocalTime) time = LocalTime(time);
                value = _TweenParent.InterpolateVector(ToProperty, time, 1f, apply);
            }
            return value;
        }

        #endregion

#if UNITY_EDITOR

        public override bool CanSeparateOrCombineChannel(bool warn = false)
        {
            if (warn) Debug.LogWarning("This channel does not support combining or separating attributes");
            return false;
        }

        public override void GUIHierarchyControls()
        {
            GUI.color = AxonColor.Default;
            GUIChannelLink();
            GUIExpandRegion();
        }

        //TODO: Optimize so the curve is only redrawn when needed

        [NonSerialized]
        private Vector3[] curvePoints;

        public void GUIRebuildCurve()
        {
        }

        public override void GUIKeyframes()
        {
            //if (TimeflowWindow.IsDrawLimited) return;// reduce draw calls to improve editor performance
            if (GUICanDraw || IsGraphLocked) {
                if (TimeflowPreferences.Current.DrawLinkedChannels && IsLinked) {
                    if (Link.Channel is TweenChannel tween) {
                        tween.GUIKeyframesDraw(true, Link.UseWorldTime ? -Link.TimeOffset : -(Link.TimeOffsetWorld - Link.Channel.TimeOffsetWorld), GUIRect);
                        //tween.GUIKeyframesDraw(true, Link.UseWorldTime ? Link.TimeOffset : 0, GUIRect);
                    }
                }
                GUIKeyframesDraw(false, TimeOffset, GUIRect);
            }
        }

        public override void GUIKeyframesDraw(bool isLink, float offsetTime, Rect rect)
        {
            //if (TimeflowWindow.IsDrawLimited) return;// reduce draw calls to improve editor performance
            Handles.BeginGUI();

            float viewTotalTime = Timeflow.Active.View.ViewEndTime - Timeflow.Active.View.ViewStartTime;
            if (viewTotalTime <= 0) return;

            float startTime = _TweenParent.StartAt.Time;
            float endTime = _TweenParent.EndAt.Time;

            bool drawMain = true;
            if (startTime > Timeflow.Active.View.ViewEndTime || endTime < Timeflow.Active.View.ViewStartTime) {
                // The track area is out of view
                drawMain = false;
            }

            float startPos = 0f;
            float endPos = rect.width;
            float height = rect.height - 4f;
            float offsety = rect.y + 2f;

            if (Timeflow.Active.View.IsGraphMode) {
                float min = Mathf.Min(_TweenParent.MinValue, _TweenParent.MaxValue);
                float max = Mathf.Max(_TweenParent.MinValue, _TweenParent.MaxValue);
                float y = Timeflow.Active.View.PositionOfValue(min, true);
                float h = Timeflow.Active.View.PositionOfValue(max, true);

                offsety = y;
                height = h - y;
            }

            float worldOffset = TimeOffsetWorldToLocal;

            startTime -= worldOffset;
            endTime -= worldOffset;

            Rect track = new Rect(rect);
            if (startTime < Timeflow.Active.View.ViewStartTime) {
                track.x = 0;
                startTime = Timeflow.Active.View.ViewStartTime;
            }
            else {
            }

            if (endTime > Timeflow.Active.View.ViewEndTime) {
                track.width = rect.width;
                endTime = Timeflow.Active.View.ViewEndTime;
            }

            startTime *= TimeScaleWorld;
            endTime *= TimeScaleWorld;

            startPos = track.x = Timeflow.Active.View.PositionOfTime(startTime, true);
            endPos = Timeflow.Active.View.PositionOfTime(endTime, true);

            float trackTotalTime = endTime - startTime;
            if (trackTotalTime == 0) {
                // No time to draw
            }
            else
            if (drawMain && ToProperty != null && !ToProperty.IsColor) {
                // Draws a curve to fit the view of the timeline or graph
                // Note that color gradients are drawn by GUIDrawColorGradient

                float min = 0;
                float max = 0;
                bool isFirst = true;
                float width = endPos - startPos;

                int count = 64;
                if (width > 128) count = 128;
                if (width > 256) count = 256;
                if (width > 512) count = 512;
                if (width > 768) count = 768;
                if (width > 1024) count = 1024;

                if (TimeflowWindow.IsDrawLimited) count = count / 2; // reduce draw calls to improve editor performance

                float timeOffset = offsetTime - worldOffset;
                //Debug.Log($"GUIKeyframesDraw:{offsetTime} startTime:{startTime} TimeOffsetWorld:{TimeOffsetWorld} worldOffset:{worldOffset} timeOffset:{timeOffset}");

                curvePoints = new Vector3[count];

                for (int i = 0; i < count; i++) {
                    float p = (float)i / (float)count;
                    float t = (startTime + (p * trackTotalTime)) - timeOffset;

                    curvePoints[i].x = startPos + (p * width);
                    curvePoints[i].y = _TweenParent.InterpolateValue(ToProperty, t * TimeScaleWorld, 1f, false);
                    curvePoints[i].z = 0f;

                    if (isFirst) {
                        isFirst = false;
                        min = max = curvePoints[i].y;
                    }
                    else {
                        if (min > curvePoints[i].y) min = curvePoints[i].y;
                        if (max < curvePoints[i].y) max = curvePoints[i].y;
                    }
                }
                if (min == max) max = min + 1f;
                float size = max - min;
                if (size > 0) {
                    for (int i = 0; i < count; i++) {
                        float n = ((curvePoints[i].y - min) / size); // Normalize
                        if (!Timeflow.Active.View.IsGraphMode) {
                            n = 1f - n; // invert (view is -y up)
                        }
                        curvePoints[i].y = offsety + (n * height); // Fit to view
                    }
                    Handles.color = ColorUtil.SetAlpha(GUIColor, isLink ? 0.25f : 1f);
                    if (!IsEnabled) Handles.color = ColorUtil.SetAlpha(Handles.color, 0.2f);
                    Handles.DrawAAPolyLine(3f, curvePoints);
                }
            }

            Handles.EndGUI();
        }

        public override void GUIGraphPass2()
        {
            GUIKeyframes();
            base.GUIGraphPass2();
        }

        public override void GUIGraphFit(bool init, bool selectedOnly)
        {
            if (_TweenParent.Timeflow != null) {
                if (init) {
                    Timeflow.Active.View.GraphMinValue = Mathf.Min(_TweenParent.MinValue, _TweenParent.MaxValue);
                    Timeflow.Active.View.GraphMaxValue = Mathf.Max(_TweenParent.MinValue, _TweenParent.MaxValue);
                }
                else {
                    Timeflow.Active.View.GraphMinValue = Mathf.Min(Timeflow.Active.View.GraphMinValue, Mathf.Min(_TweenParent.MinValue, _TweenParent.MaxValue));
                    Timeflow.Active.View.GraphMaxValue = Mathf.Max(Timeflow.Active.View.GraphMaxValue, Mathf.Max(_TweenParent.MinValue, _TweenParent.MaxValue));
                }
            }
        }
#endif
    }

}//AxonGenesis
