namespace AxonGenesis
{
    /// <summary>
    /// These bindings can only represent the default values. It isn't possible to dynamically set these values in code due to their
    /// use in Shortcut() attributes. If you change the keyboard shortcut, it will not be reflected in the menu since the value is 
    /// hard-coded in the file by necessity.
    /// </summary>
    public static class TimeflowShortcutBindings
    {
        public const string SelectionToggleEnabled = "Alpha0"; //Timeflow/View: Selection Toggle Enabled
        public const string DecreaseGrid = "Alpha1"; //Timeflow/View: Decrease Grid
        public const string IncreaseGrid = "Alpha2"; //Timeflow/View: Increase Grid
        public const string SetWorkAreaStart = "B"; //Timeflow/View: Set Work Area Start
        public const string DeselectAll = "BackQuote"; //Timeflow/View: Deselect All
        public const string TangentsTool = "C"; //Timeflow/View: Tangents Tool
        public const string GoToEnd = "End"; //Timeflow/Go to End
        public const string ScrollZoomIn = "Equals"; //Timeflow/View: Scroll Zoom In
        public const string Fit = "F"; //Timeflow/View: Fit
        public const string ToggleGraphTrackMode = "G"; //Timeflow/View: Toggle Graph-Track Mode
        public const string SnapTime = "H"; //Timeflow/View: Snap Time
        public const string GoToStart = "Home"; //Timeflow/Go to Start
        public const string GoToStartOfSelection = "I"; //Timeflow/View: Go to Start of Selection
        public const string SnapValue = "J"; //Timeflow/View: Snap Value
        public const string AddKeyframe = "K"; //Timeflow/View: Add Keyframe
        public const string SelectionToggleEnabledAlternate = "Keypad0"; //Timeflow/View: Selection Toggle Enabled (Alternate)
        public const string DecreaseGridAlternate = "Keypad1"; //Timeflow/View: Decrease Grid (Alternate)
        public const string IncreaseGridAlternate = "Keypad2"; //Timeflow/View: Increase Grid (Alternate)
        public const string ScrollZoomOutAlternate = "KeypadMinus"; //Timeflow/View: Scroll Zoom Out (Alternate)
        public const string ScrollZoomInAlternate = "KeypadPlus"; //Timeflow/View: Scroll Zoom In (Alternate)
        public const string ToggleLoop = "L"; //Timeflow/View: Toggle Loop
        public const string DecreaseSelectedChannelHeights = "LeftBracket"; //Timeflow/Decrease Selected Channel Heights
        public const string ShowMarkers = "M"; //Timeflow/View: Show Markers
        public const string ScrollZoomOut = "Minus"; //Timeflow/View: Scroll Zoom Out
        public const string SetWorkAreaEnd = "N"; //Timeflow/View: Set Work Area End
        public const string GoToEndOfSelection = "O"; //Timeflow/View: Go to End of Selection
        public const string GoToNextFrame = "PageDown"; //Timeflow/Go to Next Frame
        public const string GoToPreviousFrame = "PageUp"; //Timeflow/Go to Previous Frame
        public const string ToggleGrid = "R"; //Timeflow/View: Toggle Grid
        public const string IncreaseSelectedChannelHeights = "RightBracket"; //Timeflow/Increase Selected Channel Heights
        public const string ToggleLocalTimeScope = "S"; //Timeflow/View: Toggle Local Time Scope
        public const string ScrollZoomToggle = "Semicolon"; //Timeflow/View: Scroll Zoom Toggle
        public const string TogglePlay = "Space"; //Timeflow/Playback: Toggle Play
        public const string ToggleKeyframeBoundingBox = "T"; //Timeflow/View: Toggle Keyframe Bounding Box
        public const string ToggleWorkArea = "W"; //Timeflow/View: Toggle Work Area
        public const string SelectAll = "Ctrl+A"; //Timeflow/View: Select All
        public const string SelectionToggleLocked = "Ctrl+Alpha0"; //Timeflow/View: Selection Toggle Locked
        public const string DisplayNothing = "Ctrl+BackQuote"; //Timeflow/Display: Nothing
        public const string CopyKeyframes = "Ctrl+C"; //Timeflow/View: Copy Keyframes
        public const string DuplicateSelected = "Ctrl+D"; //Timeflow/View: Duplicate Selected
        public const string FitGraphAuto = "Ctrl+F"; //Timeflow/View: Fit Graph (Auto)
        public const string Group = "Ctrl+G"; //Timeflow/Game Object: Group
        public const string JoinSelectedTracks = "Ctrl+J"; //Timeflow/View: Join Selected Tracks
        public const string SelectionToggleLockedAlternate = "Ctrl+Keypad0"; //Timeflow/View: Selection Toggle Locked (Alternate)
        public const string EnterPrefabPrecompEditMode = "Ctrl+KeypadEnter"; //Timeflow/Game Object: Enter Prefab-Precomp Edit Mode
        public const string ExitPrefabPrecompEditMode = "Ctrl+KeypadMinus"; //Timeflow/Game Object: Exit Prefab-Precomp Edit Mode
        public const string LoopSelected = "Ctrl+L"; //Timeflow/View: Loop Selected
        public const string AddMarkerAtCurrentTime = "Ctrl+M"; //Timeflow/View: Add Marker at Current Time
        public const string GoToNextSnapTime = "Ctrl+PageDown"; //Timeflow/Go to Next Snap Time
        public const string GoToPreviousSnapTime = "Ctrl+PageUp"; //Timeflow/Go to Previous Snap Time
        public const string RenameSelectedObjectOrChannel = "Ctrl+R"; //Timeflow/View: Rename Selected Object or Channel
        public const string ToggleLockSelectedChannelHeights = "Ctrl+RightBracket"; //Timeflow/Toggle Lock Selected Channel Heights
        public const string ToggleContinuousPlay = "Ctrl+Space"; //Timeflow/Playback: Toggle Continuous Play
        public const string SnapTimesOfSelectedKeyframesQuantize = "Ctrl+U"; //Timeflow/View: Snap Times of Selected Keyframes (Quantize)
        public const string PasteKeyframesAtCurrentTime = "Ctrl+V"; //Timeflow/View: Paste Keyframes (At Current Time)
        public const string CutKeyframes = "Ctrl+X"; //Timeflow/View: Cut Keyframes
        public const string JumpToFullDuration = "Alt+Alpha0"; //Timeflow/Jump to Full Duration
        public const string JumpToMarker1 = "Alt+Alpha1"; //Timeflow/Jump to Marker 1
        public const string JumpToMarker2 = "Alt+Alpha2"; //Timeflow/Jump to Marker 2
        public const string JumpToMarker3 = "Alt+Alpha3"; //Timeflow/Jump to Marker 3
        public const string JumpToMarker4 = "Alt+Alpha4"; //Timeflow/Jump to Marker 4
        public const string JumpToMarker5 = "Alt+Alpha5"; //Timeflow/Jump to Marker 5
        public const string JumpToMarker6 = "Alt+Alpha6"; //Timeflow/Jump to Marker 6
        public const string JumpToMarker7 = "Alt+Alpha7"; //Timeflow/Jump to Marker 7
        public const string JumpToMarker8 = "Alt+Alpha8"; //Timeflow/Jump to Marker 8
        public const string JumpToMarker9 = "Alt+Alpha9"; //Timeflow/Jump to Marker 9
        public const string DisplaySelectedOnly = "Alt+BackQuote"; //Timeflow/Display: Selected Only
        public const string TrackColorsOpenColorPalette = "Alt+C"; //Timeflow/Track Colors/Open Color Palette
        public const string TrackColorsAssignRandomTrackColors = "Alt+D"; //Timeflow/Track Colors/Assign Random Track Colors
        public const string TrackColorsAssignSequentialTrackColors = "Alt+E"; //Timeflow/Track Colors/Assign Sequential Track Colors
        public const string GoToEndGlobal = "Alt+End"; //Timeflow/Go to End (Global)
        public const string GoToStartGlobal = "Alt+Home"; //Timeflow/Go to Start (Global)
        public const string SetStartOfSelectedTracks = "Alt+I"; //Timeflow/View: Set Start of Selected Tracks
        public const string SplitSelectedTracksAtCurrentTime = "Alt+J"; //Timeflow/View: Split Selected Tracks at Current Time
        public const string AutoKeyframing = "Alt+K"; //Timeflow/Auto Keyframing
        public const string LockGraph = "Alt+L"; //Timeflow/View: Lock Graph
        public const string DisplayPrevious = "Alt+LeftBracket"; //Timeflow/Display: Previous
        public const string SelectMainCamera = "Alt+M"; //Timeflow/Game Object: Select Main Camera
        public const string SetEndOfSelectedTracks = "Alt+O"; //Timeflow/View: Set End of Selected Tracks
        public const string GoToNextMarker = "Alt+PageDown"; //Timeflow/Go to Next Marker
        public const string GoToPreviousMarker = "Alt+PageUp"; //Timeflow/Go to Previous Marker
        public const string DisplayNext = "Alt+RightBracket"; //Timeflow/Display: Next
        public const string DisplaySoloSelected = "Alt+S"; //Timeflow/Display: Solo Selected
        public const string TrackColorsAssignAutoTrackColors = "Alt+T"; //Timeflow/Track Colors/Assign Auto Track Colors
        public const string DisplayEverything = "Alt+Ctrl+BackQuote"; //Timeflow/Display: Everything
        public const string SplitSelectedTracksByWorkArea = "Alt+Ctrl+J"; //Timeflow/View: Split Selected Tracks by Work Area
        public const string SaveSceneBackup = "Alt+Ctrl+S"; //Timeflow/Editor: Save Scene Backup
        public const string EnableRenderersRecursively = "Alt+Shift+Alpha1"; //Timeflow/Game Object: Enable Renderers Recursively
        public const string DisableRenderersRecursively = "Alt+Shift+Alpha2"; //Timeflow/Game Object: Disable Renderers Recursively
        public const string AddBehaviorBlend = "Alt+Shift+B"; //Timeflow/Add Behavior: Blend
        public const string DisplayAddSelectedToView = "Alt+Shift+BackQuote"; //Timeflow/Display: Add Selected to View
        public const string AddBehaviorFlyby = "Alt+Shift+F"; //Timeflow/Add Behavior: Flyby
        public const string AddBehaviorMotionPath = "Alt+Shift+M"; //Timeflow/Add Behavior: Motion Path
        public const string Precompose = "Alt+Shift+P"; //Timeflow/Precompose
        public const string DisplaySoloSelectedAppend = "Alt+Shift+S"; //Timeflow/Display: Solo Selected (Append)
        public const string AddBehaviorTween = "Alt+Shift+T"; //Timeflow/Add Behavior: Tween
        public const string DisableDebugForAllObjects = "Alt+Shift+Ctrl+B"; //Timeflow/Editor: Disable Debug For All Objects
        public const string DisplayActiveSelectionGrouped = "Alt+Shift+Ctrl+BackQuote"; //Timeflow/Display: Active Selection (Grouped)
        public const string OpenAdvancedPresets = "Alt+Shift+Ctrl+P"; //Timeflow/Advanced Presets
        public const string SetSelectedTracksToWorkArea = "Alt+Shift+Ctrl+J"; //Timeflow/View: Set Selected Tracks to Work Area
        public const string SelectDescendants = "Alt+Shift+Ctrl+Minus"; //Timeflow/Game Object: Select Descendants
        public const string AddNewTimeflow = "Alt+Shift+Ctrl+N"; //Timeflow/Add New Timeflow
        public const string TransformPastePositionOnly = "Alt+Shift+Ctrl+O"; //Timeflow/Transform: Paste Position Only
        public const string SelectAncestors = "Alt+Shift+Ctrl+Plus"; //Timeflow/Game Object: Select Ancestors
        public const string SaveSelectedPrefabs = "Alt+Shift+Ctrl+S"; //Timeflow/Game Object: Save Selected Prefabs
        public const string OpenTimeflowWindow = "Alt+Shift+Ctrl+T"; //Timeflow/Open Timeflow Window
        public const string Ungroup = "Alt+Shift+Ctrl+U"; //Timeflow/Game Object: Ungroup
        public const string PasteKeyframeTangentsOnly = "Alt+Shift+Ctrl+V"; //Timeflow/View: Paste Keyframe Tangents Only
        public const string ToggleTimeflowWindowMinimized = "Alt+Shift+Ctrl+W"; //Timeflow/Toggle Timeflow Window Minimized
        public const string Activate = "Shift+Alpha1"; //Timeflow/Game Object: Activate
        public const string Deactivate = "Shift+Alpha2"; //Timeflow/Game Object: Deactivate
        public const string SetWorkAreaStartKeepDuration = "Shift+B"; //Timeflow/View: Set Work Area Start (Keep Duration)
        public const string DisplayToggleHidden = "Shift+BackQuote"; //Timeflow/Display: Toggle Hidden
        public const string KeysOnlyTool = "Shift+C"; //Timeflow/View: Keys-Only Tool
        public const string FitTimeOnly = "Shift+F"; //Timeflow/View: Fit Time Only
        public const string QuickMenu = "Shift+T"; //Timeflow/Quick Select Object 1
        public const string QuickSelectObject1 = "Shift+F1"; //Timeflow/Quick Select Object 1
        public const string QuickSelectObject10 = "Shift+F10"; //Timeflow/Quick Select Object 10
        public const string QuickSelectObject11 = "Shift+F11"; //Timeflow/Quick Select Object 11
        public const string QuickSelectObject12 = "Shift+F12"; //Timeflow/Quick Select Object 12
        public const string QuickSelectObject2 = "Shift+F2"; //Timeflow/Quick Select Object 2
        public const string QuickSelectObject3 = "Shift+F3"; //Timeflow/Quick Select Object 3
        public const string QuickSelectObject4 = "Shift+F4"; //Timeflow/Quick Select Object 4
        public const string QuickSelectObject5 = "Shift+F5"; //Timeflow/Quick Select Object 5
        public const string QuickSelectObject6 = "Shift+F6"; //Timeflow/Quick Select Object 6
        public const string QuickSelectObject7 = "Shift+F7"; //Timeflow/Quick Select Object 7
        public const string QuickSelectObject8 = "Shift+F8"; //Timeflow/Quick Select Object 8
        public const string QuickSelectObject9 = "Shift+F9"; //Timeflow/Quick Select Object 9
        public const string SetWorkAreaEndKeepDuration = "Shift+N"; //Timeflow/View: Set Work Area End (Keep Duration)
        public const string GoToNextKeyframe = "Shift+PageDown"; //Timeflow/Go to Next Keyframe
        public const string GoToPreviousKeyframe = "Shift+PageUp"; //Timeflow/Go to Previous Keyframe
        public const string SetWorkAreaToSelected = "Shift+W"; //Timeflow/View: Set Work Area to Selected

        public const string QuickSelectAssignObject1 = "Shift+Ctrl+F1"; //Timeflow/Quick Select Object Assign 1
        public const string QuickSelectAssignObject2 = "Shift+Ctrl+F2"; //Timeflow/Quick Select Object Assign 2
        public const string QuickSelectAssignObject3 = "Shift+Ctrl+F3"; //Timeflow/Quick Select Object Assign 3
        public const string QuickSelectAssignObject4 = "Shift+Ctrl+F4"; //Timeflow/Quick Select Object Assign 4
        public const string QuickSelectAssignObject5 = "Shift+Ctrl+F5"; //Timeflow/Quick Select Object Assign 5
        public const string QuickSelectAssignObject6 = "Shift+Ctrl+F6"; //Timeflow/Quick Select Object Assign 6
        public const string QuickSelectAssignObject7 = "Shift+Ctrl+F7"; //Timeflow/Quick Select Object Assign 7
        public const string QuickSelectAssignObject8 = "Shift+Ctrl+F8"; //Timeflow/Quick Select Object Assign 8
        public const string QuickSelectAssignObject9 = "Shift+Ctrl+F9"; //Timeflow/Quick Select Object Assign 9
        public const string QuickSelectAssignObject10 = "Shift+Ctrl+F10"; //Timeflow/Quick Select Object Assign 10
        public const string QuickSelectAssignObject11 = "Shift+Ctrl+F11"; //Timeflow/Quick Select Object Assign 11
        public const string QuickSelectAssignObject12 = "Shift+Ctrl+F12"; //Timeflow/Quick Select Object Assign 12

        public const string TransformCopy = "Shift+Ctrl+I"; //Timeflow/Transform: Copy
        public const string DebugMarkLineInConsole = "Shift+Ctrl+M"; //Timeflow/Editor: Debug Mark Line in Console
        public const string SelectChildren = "Shift+Ctrl+Minus"; //Timeflow/Game Object: Select Children
        public const string TransformPaste = "Shift+Ctrl+O"; //Timeflow/Transform: Paste
        public const string GoForwardCustomTimeStep = "Shift+Ctrl+PageDown"; //Timeflow/Go Forward Custom Time Step
        public const string GoBackCustomTimeStep = "Shift+Ctrl+PageUp"; //Timeflow/Go Back Custom Time Step
        public const string SelectParents = "Shift+Ctrl+Plus"; //Timeflow/Game Object: Select Parents
        public const string TransformReset = "Shift+Ctrl+T"; //Timeflow/Transform: Reset
        public const string SnapValuesOfSelectedKeyframesQuantize = "Shift+Ctrl+U"; //Timeflow/View: Snap Values of Selected Keyframes (Quantize)
        public const string PasteKeyframesPreserveTime = "Shift+Ctrl+V"; //Timeflow/View: Paste Keyframes (Preserve Time)
    }

}

